### ISSUE TITLE
crashes on Sign In with ActivityNotFoundException

### ISSUE THREAD

**Issue by sonnyp** [swentel/indigenous-android#229]
**Describe the bug**

Indigenous crashes on IndieAuth sign in with `android.content.ActivityNotFoundException`.

**To Reproduce**
1. Go to `sign in`
2. Enter `http://5d91eb3f-0c37-426b-b7ae-0ebc7ea1e0bd.pub.cloud.scaleway.com/`
2. Click on 'SIGN IN'
4. Indigenous crashes.

**Smartphone:**
 - Device: Fairphone 2
 - Android version: 8.1.0
 - Indiegenous: 0.43 play store

**Additional context**

```
06-21 15:57:34.288  1230  3416 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=/authorize?response_type=code&redirect_uri=https://indigenous.realize.be/indigenous-callback.php&client_id=https://indigenous.realize.be&me=http://5d91eb3f-0c37-426b-b7ae-0ebc7ea1e0bd.pub.cloud.scaleway.com/&scope=create+update+delete+media+read+follow+channels+mute+block&state=6fa9a31d-3 flg=0x44000000 (has extras)} from uid 10156
06-21 15:57:34.289 29942 29942 D AndroidRuntime: Shutting down VM
06-21 15:57:34.290 29942 29942 E AndroidRuntime: FATAL EXCEPTION: main
06-21 15:57:34.290 29942 29942 E AndroidRuntime: Process: com.indieweb.indigenous, PID: 29942
06-21 15:57:34.290 29942 29942 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/authorize?response_type=code&redirect_uri=https://indigenous.realize.be/indigenous-callback.php&client_id=https://indigenous.realize.be&me=http://5d91eb3f-0c37-426b-b7ae-0ebc7ea1e0bd.pub.cloud.scaleway.com/&scope=create+update+delete+media+read+follow+channels+mute+block&state=6fa9a31d-3 flg=0x44000000 (has extras) }
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4487)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4445)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4806)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:143)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at com.indieweb.indigenous.indieauth.IndieAuthActivity$2.onClick(IndieAuthActivity.java:155)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.view.View.performClick(View.java:6294)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24770)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
06-21 15:57:34.290 29942 29942 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Does not crash with indigenous 0.34 from f-droid unfortunally I get a 404 on indigenous.abdode.pub after successfull auth so I'm unable to use it.

**Comment by sonnyp** [comment]
A previous version of Indigenous worked but I'm not sure which one I had previously.

**Comment by sonnyp** [comment]
Does not crash with indigenous 0.34 from f-droid

**Comment by swentel** [comment]
Hmm, interesting crash. And even more interesting it doesn't crash on 0.34 since the IndieAuthActivity class, which handles the sign in hasn't changed fundamentally - unless I've missed something.

I'll do some tests tomorrow, but a bit in the dark at the moment what the problem could be.

**Comment by swentel** [comment]
Actually, I think I know what causes the crash. The URL endpoints for authorization (and also micropub) in both the html or header response on that domain are all relative. Can you make those absolute and try again then ?

I'm actually not sure what the spec says about those urls whether they can be relative or not. If so, that I have to fix that as well to prepend the domain on sign in.

**Comment by sonnyp** [comment]
Thanks. I'll try with absolute URLs and let you know, regarding the spec I found this : 

https://indieauth.spec.indieweb.org/#discovery-by-clients

> The endpoints discovered MAY be relative URLs, in which case the client MUST resolve them relative to the profile URL according to [URL].

**Comment by sonnyp** [comment]
I just tried with absolute URLs and it worked like a charm.
