### ISSUE TITLE
Intermittent app crashes when opening app after using other apps for some time

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#248]
**Describe the bug**

App crashes, without an error message, and requires restarting.

**To Reproduce**

This bug is not easily reproducible, unfortunately (at this time). It appears to occur when the app hasn't been in the foreground for some time, and other apps have been used.

**Expected behavior**

App should not unexpectedly crash.

**Screenshots**

N/A

**Smartphone (please complete the following information):**

- Device: Google Pixel 3A
- Android version: 10

**Additional context**

I've only noticed it appearing since the fix for #241 went live, but it may have existed before that.

Potentially relevant error logs:

```	
11-02 14:53:22.928  1455  5667 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.indieweb.indigenous/.LaunchActivity bnds=[622,998][821,1229]} from uid 10042
11-02 14:53:22.933   870   870 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 1
11-02 14:53:22.956 25551 25551 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@367f7d0
11-02 14:53:23.012 25551 25551 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
11-02 14:53:23.079   785 25811 E ResolverController: No valid NAT64 prefix (284, <unspecified>/0)
11-02 14:53:23.556 24803 24888 I PBSessionCacheImpl: Deleted sessionId[109086320321019046] from persistence.
11-02 14:53:23.571 24803 24852 W SearchServiceCore: Abort, client detached.
11-02 14:53:23.571 24803 24852 I StreamController: cleanUpControllerScope(nowcards-15-63964f4f-680d)
11-02 14:53:23.574 24803 24852 I MicroDetectionState: Should stop hotword detection immediately - false
11-02 14:53:24.212 25551 25551 D AndroidRuntime: Shutting down VM
11-02 14:53:24.220 25551 25551 E AndroidRuntime: FATAL EXCEPTION: main
11-02 14:53:24.220 25551 25551 E AndroidRuntime: Process: com.indieweb.indigenous, PID: 25551
11-02 14:53:24.220 25551 25551 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:555)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:545)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.indieweb.indigenous.util.Preferences.getPreference(Preferences.java:59)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.indieweb.indigenous.microsub.channel.ChannelFragment$1.onResponse(ChannelFragment.java:162)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.indieweb.indigenous.microsub.channel.ChannelFragment$1.onResponse(ChannelFragment.java:124)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:78)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:106)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-02 14:53:24.220 25551 25551 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
11-02 14:53:24.225  1455  4248 W ActivityTaskManager:   Force finishing activity com.indieweb.indigenous/.MainActivity
11-02 14:53:24.237 25551 25551 I Process : Sending signal. PID: 25551 SIG: 9
11-02 14:53:24.257  1455  1804 I chatty  : uid=1000(system) InputDispatcher expire 2 lines
11-02 14:53:24.260  1455  4677 I WindowManager: WIN DEATH: Window{21d0f6 u0 com.indieweb.indigenous/com.indieweb.indigenous.MainActivity}
11-02 14:53:24.260  1455  4677 I chatty  : uid=1000(system) Binder:1455_12 expire 1 line
11-02 14:53:24.261   842   842 I Zygote  : Process 25551 exited due to signal 9 (Killed)
11-02 14:53:24.266  1455  3762 I ActivityManager: Process com.indieweb.indigenous (pid 25551) has died: vis+99 TOP
11-02 14:53:24.266  1455  1563 I chatty  : uid=1000(system) ActivityManager expire 1 line
11-02 14:53:24.285  1455  1546 W ActivityManager: setHasOverlayUi called on unknown pid: 25551
11-02 14:53:24.378 24803 24852 I StreamController: registerScope: nowcards-15-63964f4f-680d
11-02 14:53:24.727  1455  1546 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{3f7d1a2 u0 com.indieweb.indigenous/.MainActivity t-1 f}
11-02 14:53:25.085   842   842 D Zygote  : Forked child process 25825
```

**Comment by swentel** [comment]
Yeah, I've hit this one myself as well. This has been fixed by #243 - A release is scheduled for next saturday. I'm testing some new features first now on my phone the whole week to make sure those are fine.

**Comment by jamietanna** [comment]
Nice one, glad it was already on your radar. Thanks!

**Comment by swentel** [comment]
actually, just pushed a new release, hope everything is fine :)
